import os
os.system("clear")
import time
print("Oi")
print(" ")
time.sleep(1.5)
print("tudo bom?")
print(" ")
time.sleep(1.5)
print("passando pra lembrar")
print(" ")
time.sleep(1.5)
print("que eu Te amo <3")
print(" ")
time.sleep(1.5)
print("Queria saber se voce quer")
print(" ")
time.sleep(1.5)
print("...")
print(" ")
time.sleep(1.5)
print("namorar comigo?")
time.sleep(1.5)
